version: '3'

# TODO : ssl 対応
services:
  httpd:
    build:
      context: ./httpd/
    depends_on:
      - db
    ports:
      - "2345:443"
      - "2354:80"
    volumes:
      - ./httpd/entrypoint.sh:/opt/entrypoint.sh
      - ./src/Gemfile.local:/var/lib/redmine/Gemfile.local
      - ./src/files:/var/lib/redmine/files:z
      - ./src/log:/var/lib/redmine/log:Z
      - ./src/plugins:/var/lib/redmine/plugins
      - ./src/public/themes:/var/lib/redmine/public/themes
    restart: always
    entrypoint: /opt/entrypoint.sh
    extra_hosts:
      - "ad:192.168.1.10"

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "sizebook01"
      POSTGRES_USER: "redmine"
      POSTGRES_DB: "redmine"
      POSTGRES_INITDB_ARGS: "-E UTF-8"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "2346:3306"

volumes:
  postgres:
