version: "3"

services:
  nginx:
    build:
      context: .
      args:
        USER: ${USER}
        PASSWORD: test
    volumes:
      - ./html:/WWW/html
      - ./conf:/etc/nginx/conf.d
    ports:
      - 8080:80

