version: '3'

services:
  anaconda:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        user: ${user}
        password: ${password}
    ports:
      - "4000:8888" # for jupyter lab
      - "5000:5000" # for flask app
    restart: always
    volumes:
      - ./work:/home/${user}/work
      - ./config:/home/${user}/config
      - ./work/.jupyter:/home/${user}/.jupyter
    entrypoint: /home/${user}/config/entrypoint.sh
    command: ${user}
