version: '3'

services:
  anaconda:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:8888"
    volumes:
      - ./work:/workdir
      - ./config:/config
    entrypoint: /config/entrypoint.sh

