version: '3'

services:
  anaconda:
    image: continuumio/anaconda3
    ports:
      - "4000:8888"
    volumes:
      - ./work:/workdir
      - ./config:/config
    entrypoint: /config/entrypoint.sh

