version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8888"
    volumes:
      - ./work:/home/jovyan/work/
    restart: always
    command: jupyter notebook --NotebookApp.password='sha1:667ccb914469:b2303e608226c018749e4de032ec05f5e9a9776c'
