version: '3'

services:
  engine:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        user: "kitamura"
        passwd: "passwd"
    restart: always
    ports:
      - "33333:22"
    volumes:
      - ~/.ssh:/home/kitamura/.ssh
