MAINTENER y-kitamu ymyk6602@gmail.com

FROM ubuntu:18.04

RUN apt-get update -y

# ssh
RUN apt-get install openssh-server -y

# c++
RUN apt-get install build-essential gcc -y
RUN apt-get install cmake -y
