version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8888:80"
    depends_on:
      - php
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
        
  php:
    image: php:7-fpm-alpine
    volumes:
      - ./html:/var/www/html
