version: '3'

services:
  node:
    hostname: node_dev
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "32323:22"
      - "3000:3000" # for electron gui
      - "9898:8000" # for fastapi
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ${HOME}/work:${HOME}/work
      - ${HOME}/.ssh:${HOME}/.ssh
      - ${HOME}/.bashrc:${HOME}/.bashrc
    entrypoint: /usr/sbin/sshd -D
    privileged: true
    restart: always
