version: "3"

services:
  jupyter:
    build:
      context: .
      args:
        user: ${USER}
        password: ${password}
    ports:
      - "4000:8888"
    restart: always
    volumes:
      - ~/work:/home/${USER}/work
      - ./config:/home/${USER}/config
      - ./config/.jupyter:/home/${USER}/.jupyter
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
    entrypoint: /home/${USER}/config/entrypoint.sh
    command: ${USER}
