version: '3'

services:
  python:
    hostname: python_dev
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "32222:22" # ssh
      - "5088:5000" # jupyter lab
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/work:${HOME}/work
      - ${HOME}/dataset:${HOME}/dataset
      - ${HOME}/.ssh:${HOME}/.ssh
      - ${HOME}/.bashrc:${HOME}/.bashrc
      - ./.jupyter:${HOME}/.jupyter
    entrypoint: /tmp/entrypoint.sh
    environment:
      USER_NAME: ${USER}
    privileged: true
    restart: always

  tensorboard:
    hostname: tensorboard
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ${HOME}/work:${HOME}/work
    entrypoint: tensorboard --logdir=${HOME}/work/Kaggle/logs --bind_all
    restart: always
