# ref : https://github.com/ymym3412/mlflow-docker-compose/blob/master/docker-compose.yaml
version: '3'
services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresql
    command: postgresql:5432

  postgresql:
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    # volumes:
    #   - mlflowdb:/var/lib/postgresql/data
    hostname: postgresql
    restart: always

  mlflow:
    build: .
    container_name: mlflow
    ports:
      - 7080:80
    depends_on:
      - postgresql
      - waitfordb
    environment:
      DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${DB_NAME}
      ARTIFACTS_PATH: ftp://${FTP_USER_NAME}:${FTP_USER_PASS}@mlflowftpd${FTP_USER_HOME}
      # AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      # AWS_CREDENTIALS: /opt/credentials

  mlflowftpd:
    image: stilliard/pure-ftpd:latest
    ports:
      - 21:21
      - 30000-30009:30000-30009
    # volumes:
    #   - artifacts:${FTP_USER_HOME}
    environment:
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: ${FTP_USER_HOME}
      PUBLICHOST: ${PUBLICHOST}
    hostname: mlflowftpd

volumes:
  # mlflowdb:
  artifacts:
